version: 2.1

orbs:
  c: rafaelostertag/common-orb@1.6.1

jobs:
  build-docker-image:
    parameters:
      dir:
        type: string
      remote_docker:
        type: boolean
        default: true
      executor:
        type: executor
    executor: <<parameters.executor>>
    steps:
      - c/quarkus-native-docker-image:
          dir: <<parameters.dir>>
          remote_docker: <<parameters.remote_docker>>

  build-multi-arch-manifest:
    parameters:
      remote_docker:
        type: boolean
        default: true
      image:
        type: string
    executor: c/java11-build-amd64
    steps:
      - c/docker-multi-arch-manifest:
          image: <<parameters.image>>
          remote_docker: <<parameters.remote_docker>>

  trigger-angular-api-build:
    docker:
      - image: cimg/openjdk:11.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Trigger angular api build
          command: .circleci/trigger-angular-api-build.sh

  trigger-helm-deployment:
    executor: c/java11-build-amd64
    steps:
      - checkout
      - run:
          name: Trigger helm deployment
          command: .circleci/trigger-helm-deployment.sh

workflows:
  build-any-branch:
    jobs:
      - c/maven-build-and-test:
          name: build-and-test
          sonar-project-key: "ch.guengel.astro.server:astro-server-parent"
          context:
            - sonar
            - repository-read
      - c/maven-deploy-artifacts:
          name: deploy-maven-artifact
          requires:
            - build-and-test
          context:
            - maven-repository-write
      - trigger-angular-api-build:
          context:
            - circle-ci
          requires:
            - deploy-maven-artifact
      - build-docker-image:
          name: astro-server-docker-image-amd64
          executor: c/graalvm-native-amd64
          dir: "server"
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
      - build-docker-image:
          name: catalog-fetcher-docker-image-amd64
          executor: c/graalvm-native-amd64
          dir: "catalog-fetcher"
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
      - build-docker-image:
          name: catalog-fetcher-docker-image-arm64
          executor: c/graalvm-native-arm64
          dir: "catalog-fetcher"
          remote_docker: false
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
      - build-docker-image:
          name: astro-server-docker-image-arm64
          executor: c/graalvm-native-arm64
          dir: "server"
          remote_docker: false
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
      - build-multi-arch-manifest:
          name: build-multi-arch-server-manifest
          image: "rafaelostertag/astro-server"
          context:
            - docker-build
          requires:
            - astro-server-docker-image-amd64
            - astro-server-docker-image-arm64
      - build-multi-arch-manifest:
          name: build-multi-arch-catalog-fetcher-manifest
          image: "rafaelostertag/astro-server-catalog-fetcher"
          context:
            - docker-build
          requires:
            - catalog-fetcher-docker-image-amd64
            - catalog-fetcher-docker-image-arm64
      - trigger-helm-deployment:
          filters:
            branches:
              only: master
          context:
            - circle-ci
          requires:
            - build-multi-arch-catalog-fetcher-manifest
            - build-multi-arch-server-manifest

  daily-dependency-check:
    triggers:
      - schedule:
          cron: "21 4 * * *"
          filters:
            branches:
              only:
                - master
                - develop
    jobs:
      - c/maven-dependency-check:
          context:
            - repository-read
