version: 2.1

orbs:
  c: rafaelostertag/common-orb@1.14.0

workflows:
  build-any-branch:
    jobs:
      - c/maven-build-and-test:
          name: build-and-test
          sonar-project-key: "ch.guengel.astro.server:astro-server-parent"
          context:
            - sonar
            - repository-read
      # Artifacts should always be deployed. Used to build server JS API, also for dev versions
      - c/maven-deploy-artifacts:
          name: deploy-maven-artifact
          requires:
            - build-and-test
          context:
            - maven-repository-write
      - c/maven-trigger-pipeline-with-version:
          name: trigger-astro-server-angular
          project-name: astro-server-angular
          allow-snapshot: true
          context:
            - circle-ci
          requires:
            - deploy-maven-artifact
      - c/maven-quarkus-native-docker-image:
          name: astro-server-docker-image-amd64
          executor: c/graalvm-native-amd64
          dir: "server"
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
      - c/maven-quarkus-native-docker-image:
          name: catalog-fetcher-docker-image-amd64
          executor: c/graalvm-native-amd64
          dir: "catalog-fetcher"
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
      - c/maven-quarkus-native-docker-image:
          name: catalog-fetcher-docker-image-arm64
          executor: c/graalvm-native-arm64
          dir: "catalog-fetcher"
          remote_docker: false
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
      - c/maven-quarkus-native-docker-image:
          name: astro-server-docker-image-arm64
          executor: c/graalvm-native-arm64
          dir: "server"
          remote_docker: false
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
      - c/maven-multi-arch-manifest:
          name: build-multi-arch-server-manifest
          image: "rafaelostertag/astro-server"
          context:
            - docker-build
          requires:
            - astro-server-docker-image-amd64
            - astro-server-docker-image-arm64
      - c/maven-multi-arch-manifest:
          name: build-multi-arch-catalog-fetcher-manifest
          image: "rafaelostertag/astro-server-catalog-fetcher"
          context:
            - docker-build
          requires:
            - catalog-fetcher-docker-image-amd64
            - catalog-fetcher-docker-image-arm64
      - c/maven-trigger-pipeline-with-version:
          name: trigger-helm-deployment
          project-name: astro-server-helm
          filters:
            branches:
              only: master
          context:
            - circle-ci
          requires:
            - build-multi-arch-catalog-fetcher-manifest
            - build-multi-arch-server-manifest

  daily-dependency-check:
    triggers:
      - schedule:
          cron: "21 4 * * *"
          filters:
            branches:
              only:
                - master
                - develop
    jobs:
      - c/maven-dependency-check:
          context:
            - repository-read
